### PR TITLE
feat: show plugin toolbar (sidebar) on hover

### PR DESCRIPTION
**Pull request by hejtful**
Relevant Trello card: https://trello.com/c/ZYLCKgNQ

Reviewers assigned just in case you're interested, feel free to skip, of course.

### CODE REVIEW

**Review by kulla — APPROVED** [review]

**Comment by kulla** [comment]
@elbotho Can you check https://demo-git-feat-plugin-icons-on-hover-edtr-io.vercel.app/?path=/story/article-initial-state--editor when you hover over a solution?

**Review by elbotho — APPROVED** [review]
Thanks @hejtful!
Code looks good. For the bigger changes ahead I'd like to explore if we can handle at least the hover without state changes (css only) but for now this is great.
I allowed myself changed some styles.

**Comment by elbotho** [comment]
> Can you check https://demo-git-feat-plugin-icons-on-hover-edtr-io.vercel.app/?path=/story/article-initial-state--editor when you hover over a solution?

@kulla looks fine for me, do you have a screenshot of something wrong? :)

**Comment by elbotho** [comment]
oh wow, build here take even longer than in the frontend 😮

**Pull request merged**
