### PR TITLE
improving math input

### LINKED ISSUE #138: Improving visual math input
Some ideas to improve the visual math input:

- exponents with up-arrow
- indices with down-arrow
- auto-commands for pi, alpha, beta, gamma, delta
- disallow exponents for empty fields

### PR DESCRIPTION
**Pull request by Entkenntnis**
closes #138

### CODE REVIEW

**Comment by Entkenntnis** [comment]
thank you for the bug report, I can confirm this behaviour and will investigate it soon

**Comment by Knorrke** [comment]
Does happen in the current version too, so its probably not connected to this PR.

Regarding the dependency: @inyono said that if we've already built mathquill, then publishing is done simply by running `yarn publish` (which needs the login for our npm account). So I would suggest to try that and then either update the dependency in react-mathquill or forking that too.

**Comment by Entkenntnis** [comment]
Mobile input is not a high priority, so I've added a workaround (the input is processed, but with a lag) and leave it for now

**Comment by Knorrke** [comment]
This actually is not a mobile only bug. We have to make sure, that the formula is updated when we switch focus to an other plugin. Could adress that in a different PR though

**Pull request merged**
