### PR TITLE
feat: add text plugin 

### LINKED ISSUE #8: Add Slate plugin

### LINKED ISSUE #11: babel config: Missing class properties transform.
```
 SyntaxError: C:\Users\Benjamin\workspace\edtr-io\edtr-io\packages\plugin-text\src\controls\index.tsx: Missing class properties transform.
```

### PR DESCRIPTION
**Pull request by Knorrke**
## Added:
- Add text plugin with slate v44 (closes #8) containing:
  - [X] richtext editing tools
  - [X] Link

- UI:
  - [X] use overlay for link settings
  - [x] keyboard shortcuts to open Settings Overlay (Press Enter when settings cog is shown), Bold (Press B) and Italic (Press I)

- Core:
   - [x] Handle plugins with deserialize / serialize options

## Fixed
 - Chore: fix #11 

## Not included in this PR / further TODOs:
  - Katex
  - handle pasting links
  - fix blur/focus issues of overlay input fields <-> slate

### CODE REVIEW

**Comment by inyono** [comment]
The focus / blur issues between multiple slate instances should mostly be fixed with the stuff in #12.

**Comment by Knorrke** [comment]
ping @inyono tests break, because I have a dependency to `edtr-io/ui` in core now, which I _could_ add to the dependencies, but doesn't seem very sane to have a ui dependency in core... Any suggestions how to do this properly?

Also: Somehow my `ref` doesn't work

**Comment by Knorrke** [comment]
This needs a bit of rework because of the breaking changes in #18 regarding state and (de-)serialization

**Comment by Knorrke** [comment]
commit history is messed up - I opened a new PR #19

**Comment by inyono** [comment]
superseded by #19

**Pull request closed without merging**
