### PR TITLE
highlight and table plugin improvements

### PR DESCRIPTION
**Pull request by metzgaria**

### CODE REVIEW

**Comment by Knorrke** [comment]
@inyono as far as i could tell, it wasn't possible to handle the event in EditorTextarea, since `e.preventDefault()` disables the textarea functionality and `e.stopPropagation()` didnt worl (maybe the core already handled it by then?). So we had to implement the onKeyDown of the plugin config, which does have very little information... Maybe we have to change the api from core there?

**Comment by inyono** [comment]
Maybe it works if we pass some information to the event (e.g. by setting a key edtrEventHandled).

**Comment by inyono** [comment]
The changes regarding add button in rows plugin are now in its own PR #175

**Comment by inyono** [comment]
Manually merged since GitHub PRs aren't working correctly atm

**Pull request closed without merging**
